### ISSUE TITLE
Low-Level Data

### ISSUE THREAD

**Issue by dsanders11** [jdstroy/JavaPoly#1]
This isn't really an "issue" but I wasn't sure where else to put it to get an answer, since I don't see a mailing list associated to the project.

The project looks very interesting, and I was able to run some simple examples without too much difficulty - very cool.

I'd like to use the project to interface with the [zxing library](https://github.com/zxing/zxing), but haven't had much luck getting a basic example with QR codes working. The difficulty is I'm unsure of how to pass low-level data from JavaScript to the Java code in this case. Specifically I need to hand off image data. I realize conversion of high-level classes isn't going to work here, but I was thinking the raw data could be handed off and the appropriate class reconstructed in the Java code.

Is there more information on how the fuzzy method matching works? I tried a basic example of a Java method which took a single `byte[]` variable and tried to call it from JavaScript with no luck. I tried with the argument in JavaScript being either `new Array()` or `new Int8Array(2)` but neither worked. What JavaScript class would possibly match with `byte[]`? Seemed like `Int8Array` would be the obvious choice.

Any more information would be much appreciated, as being able to use zxing directly would save porting it to JavaScript which is my only alternative.

**Comment by jdstroy** [comment]
Hey there!

You just happened to stumble across my own copy of JavaPoly. :) Yes, it's an interesting project, indeed!  Unfortunate that I don't actually work on it.

You might want to take a look at [issue 124](http://git.javadeploy.net/jimsproch/JavaPoly/issues/124) in the upstream issue tracker.  Let me know if that helps.

Cheers!

-J
