### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by Eduard1997** [jdstroy/JavaPoly#4]
Hi!
I've created a script in my html file, like this: `<script src="https://www.javapoly.com/javapoly.js"></script>`, but i get an error in console that says: net:: ERR_INSECURE_RESPONSE. I've made some research and I think SSL Certificate is expired.

**Comment by jdstroy** [comment]
Hello,

Sorry for the long delay in response.  I'm not actually the owner of JavaPoly!  I just cloned a mirror of it here on Github.  You probably want to try contacting Jim Sproch instead; see the original repository at http://git.javadeploy.net/jimsproch/JavaPoly
